name: Update README on Main Branch Changes

on:
  push:
    branches:
      - main # Triggers only when commits are pushed to the main branch
  schedule:
    - cron: '0 0 * * *' # Optionally, run daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with LeetCode Stats
        id: update_readme
        run: |
          # Define the LeetCode username
          LEETCODE_USERNAME="zishnav"

          # Fetch the LeetCode stats card URL
          LEETCODE_CARD_URL="https://leetcard.jacoblin.cool/${LEETCODE_USERNAME}"

          # Generate the updated LeetCode stats markdown
          LEETCODE_MARKDOWN="![LeetCode Stats](${LEETCODE_CARD_URL})"

          # Add the stats to the README
          if grep -q "LeetCode Stats" README.md; then
            sed -i "s|!\[LeetCode Stats\](.*)|${LEETCODE_MARKDOWN}|" README.md
          else
            echo "---" >> README.md
            echo "### LeetCode Stats" >> README.md
            echo "${LEETCODE_MARKDOWN}" >> README.md
          fi

          # Add the last updated timestamp
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          if grep -q "Last updated on:" README.md; then
            sed -i "s/Last updated on:.*/Last updated on: \`${DATE}\`/" README.md
          else
            echo "---" >> README.md
            echo "_Last updated on: \`${DATE}\`_" >> README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Check for changes and commit
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README with LeetCode stats and timestamp"
            git push
          fi
