name: Update README on Main Branch Changes

on:
  push:
    branches:
      - main # Triggers only when commits are pushed to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js (optional if you need JavaScript tooling)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update README
        id: update_readme
        run: |
          # Get the current date in UTC
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          # Use a unique placeholder or line at the bottom of the README to update the date
          if grep -q "Last updated on:" README.md; then
            sed -i "s/Last updated on:.*/Last updated on: \`${DATE}\`/" README.md
          else
            echo "---" >> README.md
            echo "_Last updated on: \`${DATE}\`_" >> README.md
          fi

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Check for changes and commit
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README with latest date: ${{ steps.update_readme.outputs.DATE }}"
            git push
          fi
